### ISSUE TITLE
Yaml Loader with File Loader

### ISSUE THREAD

**Issue by brenwell** [eemeli/yaml-loader#10]
Hey there, nice little library. Thanks.

Anyway to get yaml to json files

``` javascript
file-loader!json-loader!yaml-loader?name=[path][hash]-[name].[ext]"
```

src/
     - de.yaml
     - cs.yaml

dest/
    - de.json
    - cs.json

Cheers

**Comment by okonet** [comment]
I'd try to skip `json-loader` since it is the one that produces the JS object. Yaml-loader returns the string.

**Comment by aje4u2i** [comment]
This is my yaml file contents:
---
myfile:
  - you: have to
    put: a newline character as the last line of this file


while parsing with yaml-loader it shows:
ERROR in ./~/json-loader!./~/yaml-loader!./src/layouts/file.yaml
Module build failed: YAMLException: end of the stream or a document separator is expected at line 2, column 10:
        "myfile": [

**Comment by eemeli** [comment]
Closing, as the Webpack API for loader config has updated rather significantly since 2016 and the original issue is rather out of date. Currently, this is how you need to configure the loader:

```js
{
  test: /\.ya?ml$/,
  type: 'json',
  use: 'yaml-loader'
}
```

The comment by @aje4u2i is a completely separate issue in the version of `js-yaml` that was used, and is fixed by the switch to using `yaml`.
